apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-connector-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Додано, щоб відповідало PV
  resources:
    requests:
      storage: 1Gi  # Додано, щоб збігалося з PV
  storageClassName: standard  # Додано StorageClass, щоб відповідало PV
  volumeName: mysql-connector-pv  # Явна прив'язка до PV