apiVersion: v1
kind: Service
metadata:
  name: wildfly-service
  namespace: default
spec:
  selector:
    app: wildfly
  ports:
    - name: http
      protocol: TCP
      port: 8180
      targetPort: 8180
      nodePort: 31366
    - name: https
      protocol: TCP
      port: 8444
      targetPort: 8444
      nodePort: 31367
    - name: admin-http
      protocol: TCP
      port: 9991
      targetPort: 9991
      nodePort: 31368
    - name: admin-https
      protocol: TCP
      port: 9994
      targetPort: 9994
      nodePort: 31369
  type: NodePort
