apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wildfly
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      initContainers:
        - name: setup-mysql-driver
          image: busybox
          command: ['sh', '-c']
          args:
            - mkdir -p /opt/jboss/wildfly/modules/com/mysql/main && cp /mnt/mysql-connector-j-9.1.0.jar /opt/jboss/wildfly/modules/com/mysql/main/ && echo '<?xml version="1.0" encoding="UTF-8"?><module xmlns="urn:jboss:module:1.1" name="com.mysql"><resources><resource-root path="mysql-connector-j-9.1.0.jar"/></resources><dependencies><module name="javax.api"/><module name="javax.transaction.api"/></dependencies></module>' > /opt/jboss/wildfly/modules/com/mysql/main/module.xml
          volumeMounts:
            - name: mysql-driver
              mountPath: /mnt
      containers:
        - name: wildfly
          image: jboss/wildfly:latest
          ports:
            - containerPort: 8080
            - containerPort: 9990
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: mysql-driver
              mountPath: /mnt
            - name: user-session-storage
              mountPath: /app/data/sessions
            - name: wildfly-config
              mountPath: /opt/jboss/wildfly/standalone/configuration/standalone.xml
              subPath: standalone.xml
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120  # Збільшений час очікування
            periodSeconds: 20         # Менша частота перевірок
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 150  # Додатковий час для повного запуску сервісу
            periodSeconds: 20         # Перевірка кожні 20 секунд
      volumes:
        - name: mysql-driver
          persistentVolumeClaim:
            claimName: mysql-connector-pvc
        - name: user-session-storage
          persistentVolumeClaim:
            claimName: user-session-pvc
        - name: wildfly-config
          configMap:
            name: wildfly-config
