apiVersion: v1
kind: Service
metadata:
  name: wildfly-service
  namespace: default
spec:
  selector:
    app: wildfly
  ports:
    - name: http
      protocol: TCP
      port: 8080  # Замість 8180
      targetPort: 8080  # Замість 8180
      nodePort: 31366
    - name: https
      protocol: TCP
      port: 8443  # Якщо потрібен HTTPS порт
      targetPort: 8443  # Змініть залежно від конфігурації WildFly
      nodePort: 31367
    - name: admin-http
      protocol: TCP
      port: 9990  # Замість 9991
      targetPort: 9990  # Замість 9991
      nodePort: 31368
    - name: admin-https
      protocol: TCP
      port: 9993  # Замість 9994
      targetPort: 9993  # Замість 9994
      nodePort: 31369
  type: NodePort
